"""Added score column

Revision ID: 2dcfdadef70b
Revises: 
Create Date: 2026-02-14 20:56:40.323136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2dcfdadef70b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('journal_entry')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('journal_entry',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('mood', sa.VARCHAR(length=20), nullable=False),
    sa.Column('entry', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
